version: '3.8'
services:
  react-app:
    container_name: vuejs-container
    image: vuejs
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./node_modules:/node_modules/
    ports:
      - 8080:8080