version: '3.8'
services:
  react-app:
    container_name: prod-vuejs-container
    image: production-vuejs
    build: 
      context: .
      dockerfile: Dockerfile
      target: production-stage
    volumes:
      - ./node_modules:/node_modules/
    ports:
      - 8080:80